#################################################################
## Doorbell automation
#################################################################

- id: doorbell_ringing_daytime
  alias: Doorbell ringing daytime
  trigger:
    platform: mqtt
    topic: home/outdoors/doorbell
    payload: 'on'
  condition:
    condition: time
    after: '19:00:00'
    before: '07:00:00'
  action:
    - service: shell_command.sonos_play_doorbell
    - service: shell_command.doorbell_notification
    - service: notify.iOS
      data:
        message: "Dörrklockan ringer!"
        data:
          push:
            category: camera
          entity_id: camera.huvudentren
          
- id: doorbell_ringing_nighttime
  alias: Doorbell ringing nighttime
  trigger:
    platform: mqtt
    topic: home/outdoors/doorbell
    payload: 'on'
  condition:
    condition: time
    after: '07:00:00'
    before: '19:00:00'
  action:
    - service: shell_command.sonos_play_doorbell_night
    - service: shell_command.doorbell_notification
    - service: notify.iOS
      data:
        message: "Dörrklockan ringer!"
        data:
          push:
            category: camera
          entity_id: camera.huvudentren

#################################################################
## Turn on lights at sunset
#################################################################

- id: evening_lighting_on
  alias: Evening lighting on
  trigger:
    platform: sun
    event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.frontyard_lights
        - group.backyard_lights
    - service: notify.pushbullet
      data:
        title: "Home Assistant"
        message: "God kväll, tänder utomhusbelysningen."
        target: !secret pushbullet_channel
    - service: notify.iOS
      data_template:
        message: "God kväll, tänder utomhusbelysningen."
        data:
          push:
            badge: 5
    - condition: state
      entity_id: alarm_control_panel.alarm_1
      state: disarmed
    - service: shell_command.sonos_say
      data_template:
        say: '{{"Tänder utomhusbelysningen." | urlencode}}'
        volume: '40'

#################################################################
## Turn off lights at 12am
#################################################################

- id: evening_lighting_off
  alias: Evening lighting off
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.frontyard_lights
        - group.backyard_lights

#################################################################
## Turn on lights before sunrise
#################################################################

- id: morning_lighting_on
  alias: Morning lighting on
  trigger:
    platform: time
    at: '5:00:00'
  action:
    - condition: sun
      before: sunrise
    - service: homeassistant.turn_on
      entity_id:
        - group.frontyard_lights
        - group.backyard_lights

#################################################################
## Turn off lights at sunrise
#################################################################

- id: morning_lighting_off
  alias: Morning lighting off
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.frontyard_lights
        - group.backyard_lights
    - service: notify.pushbullet
      data:
        title: "Home Assistant"
        message: "God morgon, stänger av utomhusbelysningen."
        target: !secret pushbullet_channel
    - service: notify.iOS
      data:
        message: "God morgon, stänger av utomhusbelysningen."
        data:
          push:
            badge: 5
    - condition: state
      entity_id: alarm_control_panel.alarm_1
      state: disarmed
    - service: shell_command.sonos_say
      data_template:
        say: '{{"Släcker utomhusbelysningen." | urlencode}}'
        volume: '50'

#################################################################
## HASS Related
#################################################################

- id: heal_zwave_network
  alias: Heal Z-Wave Network
  trigger:
    platform: time
    at: '2:31:00'
  action:
    service: zwave.heal_network

- id: update_available_notification
  alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.pushbullet
      data_template:
        title: "Home Assistant"
        message: "HomeAssistant {{ states('updater.updater') }} is now available!"
        target: !secret pushbullet_channel
    - service: notify.iOS
      data_template:
        message: "HomeAssistant {{ states('updater.updater') }} is now available!"
        data:
          push:
            badge: 1
            
#################################################################
## Turn off lights when alarm is armed
#################################################################
- id: turn_off_light_when_alarm_is_armed
  alias: Turn off light when alarm is armed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_1
      to: 'armed_away'
    - platform: state
      entity_id: alarm_control_panel.alarm_1
      to: 'armed_home'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.hallway_lights

#################################################################
## Sonos Play Favorite 
#################################################################

- id: start_sonos_favorite
  alias: Start Sonos Favorite
  trigger:
  - platform: state
    entity_id: input_select.sonos_favorites
  action:
    - service: shell_command.sonos_control_shuffle_off
    - service: shell_command.sonos_volume_20
    - service_template: >
        shell_command.sonos_favorite_{{states.input_select.sonos_favorites.state.lower().replace(" ", "_").replace("-", "").replace(".", "")}}

#################################################################
## Sonos Volume 
#################################################################

- id: sonos_volume_kitchen
  alias: Sonos Volume - Kitchen
  trigger:
    - platform: state
      entity_id: input_slider.sonos_kitchen_volume
  action:
    - service: shell_command.sonos_volume
      data_template:
        speaker: 'kitchen'
        volume: '{{ trigger.to_state.state | int }}'

- id: sonos_volume_outdoors
  alias: Sonos Volume - Outdoors
  trigger:
    - platform: state
      entity_id: input_slider.sonos_outdoors_volume
  action:
    - service: shell_command.sonos_volume
      data_template:
        speaker: 'outdoors'
        volume: '{{ trigger.to_state.state | int }}'

- id: sonos_volume_living_room
  alias: Sonos Volume - Living room
  trigger:
    - platform: state
      entity_id: input_slider.sonos_living_room_volume
  action:
    - service: shell_command.sonos_volume
      data_template:
        speaker: 'living%20room'
        volume: '{{ trigger.to_state.state | int }}'

# set input_slider when volume changes elsewhere
- id: sonos_volume_set_kitchen_slider
  alias: Sonos Volume - Set kitchen slider
  trigger:
    - platform: state
      entity_id: media_player.kitchen
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.sonos_kitchen_volume
        value: '{{ states.media_player.kitchen.attributes.volume_level * 100 | int }}'

- id: sonos_volume_set_outdoors_slider
  alias: Sonos Volume - Set outdoors slider
  trigger:
    - platform: state
      entity_id: media_player.outdoors
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.sonos_outdoors_volume
        value: '{{ states.media_player.outdoors.attributes.volume_level * 100 | int }}'

- id: sonos_volume_set_living_room_slider
  alias: Sonos Volume - Set living room slider
  trigger:
    platform: state
    entity_id: media_player.living_room
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.sonos_living_room_volume
        value: '{{ states.media_player.living_room.attributes.volume_level * 100 | int }}'

