#################################################################
## Turn on lights at sunset
#################################################################

- alias: Evening lighting on
  trigger:
    platform: sun
    event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.frontyard_lights
        - group.backyard_lights
    - service: notify.pushbullet
      data:
        title: "Home Assistant"
        message: "God kväll, tänder utomhusbelysningen."
        target: !secret pushbullet_channel
    - service: notify.iOS
      data_template:
        message: "God kväll, tänder utomhusbelysningen."
        data:
          push:
            badge: 5
    - condition: state
      entity_id: alarm_control_panel.alarm_1
      state: disarmed
    - service: shell_command.sonos_say
      data_template:
        say: '{{"Tänder utomhusbelysningen." | urlencode}}'
        volume: '50'

#################################################################
## Turn off lights at 12am
#################################################################

- alias: Evening lights off
  trigger:
    platform: time
    after: '00:00:00'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.frontyard_lights
        - group.backyard_lights
