- alias: Sonos Volume - Kitchen
  trigger:
    - platform: state
      entity_id: input_slider.sonos_kitchen_volume
  action:
    - service: shell_command.sonos_volume
      data_template:
        speaker: 'kitchen'
        volume: '{{ trigger.to_state.state | int }}'

- alias: Sonos Volume - Outdoors
  trigger:
    - platform: state
      entity_id: input_slider.sonos_outdoors_volume
  action:
    - service: shell_command.sonos_volume
      data_template:
        speaker: 'outdoors'
        volume: '{{ trigger.to_state.state | int }}'

- alias: Sonos Volume - Living room
  trigger:
    - platform: state
      entity_id: input_slider.sonos_living_room_volume
  action:
    - service: shell_command.sonos_volume
      data_template:
        speaker: 'living%20room'
        volume: '{{ trigger.to_state.state | int }}'

# set input_slider when volume changes elsewhere
- alias: Sonos Volume - Set kitchen slider
  trigger:
    - platform: state
      entity_id: media_player.kitchen
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.sonos_kitchen_volume
        value: '{{ states.media_player.kitchen.attributes.volume_level * 100 | int }}'

- alias: Sonos Volume - Set outdoors slider
  trigger:
    - platform: state
      entity_id: media_player.outdoors
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.sonos_outdoors_volume
        value: '{{ states.media_player.outdoors.attributes.volume_level * 100 | int }}'

- alias: Sonos Volume - Set living room slider
  trigger:
    platform: state
    entity_id: media_player.living_room
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.sonos_living_room_volume
        value: '{{ states.media_player.living_room.attributes.volume_level * 100 | int }}'
