###########################################
#    Xiaomi Mi Flora
###########################################

- platform: miflora
  mac: C4:7C:8D:61:D4:5E
  name: flower_1
  cache: 3600
  force_update: false
  monitored_conditions:
   - moisture
   - light
   - temperature
   - conductivity
   - battery
