###########################################
#    Sonos Sensors
###########################################

- platform: command_line
  name: sonos_kitchen_shuffle_status
  command: /usr/bin/curl -X GET http://10.0.0.90:5005/kitchen/state | grep -o -P '(?<=\"shuffle\":).*(?=,)'

- platform: command_line
  name: sonos_living_room_shuffle_status
  command: /usr/bin/curl -X GET http://10.0.0.90:5005/living%20room/state | grep -o -P '(?<=\"shuffle\":).*(?=,)'
  
- platform: command_line
  name: sonos_kitchen_repeat_status
  command: /usr/bin/curl -X GET http://10.0.0.90:5005/kitchen/state | grep -o -P '(?<=\"repeat\":\").*(?=",)'

- platform: command_line
  name: sonos_living_room_repeat_status
  command: /usr/bin/curl -X GET http://10.0.0.90:5005/living%20room/state | grep -o -P '(?<=\"repeat\":\").*(?=",)'
  
- platform: command_line
  name: sonos_kitchen_crossfade_status
  command: /usr/bin/curl -X GET http://10.0.0.90:5005/kitchen/state | grep -o -P '(?<="crossfade":).*(?=})' | sed s'/.$//'
  
- platform: command_line
  name: sonos_living_room_crossfade_status
  command: /usr/bin/curl -X GET http://10.0.0.90:5005/living%20room/state | grep -o -P '(?<="crossfade":).*(?=})' | sed s'/.$//'
  
- platform: command_line
  name: sonos_living_room_next_song
  command: /usr/bin/curl -X GET http://10.0.0.90:5005/living%20room/state | egrep -o '\"nextTrack\".*' | awk -F\" '{print $10"<br />"$6}'

- platform: command_line
  name: sonos_kitchen_next_song
  command: /usr/bin/curl -X GET http://10.0.0.90:5005/kitchen/state | egrep -o '\"nextTrack\".*' | awk -F\" '{print $10"<br />"$6}'

