###########################################
#    Unifi Switch Status
###########################################

- platform: command_line
  name: unifi_switch_uptime
  command: "sed -n 's/uptime: //p' /home/homeassistant/unifi_switch_status.log"
      
- platform: command_line
  name: unifi_switch_temp
  command: "sed -n 's/temp: //p' /home/homeassistant/unifi_switch_status.log"
  unit_of_measurement: "°C"

- platform: command_line
  name: unifi_switch_memusage
  command: "sed -n 's/mem: //p' /home/homeassistant/unifi_switch_status.log"
  unit_of_measurement: "%"

- platform: command_line
  name: unifi_switch_cpuload
  command: "sed -n 's/cpu: //p' /home/homeassistant/unifi_switch_status.log"
